---
- apt: update_cache=yes

- name: Install apt-transport-https
  apt: name=apt-transport-https force=yes

- name: Install software-properties-common
  apt: name=software-properties-common force=yes

- name: Add repo
  apt_repository: repo="deb https://clusterhq-archive.s3.amazonaws.com/ubuntu/14.04/amd64 /"

- apt: update_cache=yes

- name: Install plugin
  apt: name=clusterhq-flocker-docker-plugin force=yes

- name: Create flocker config directory
  file: path=/etc/flocker state=directory

- name: Copy cluster crt
  copy:
    src: bakedcerts/cluster.crt
    dest: /etc/flocker/cluster.crt

- name: Copy control key
  copy:
    src: bakedcerts/control.key
    dest: /etc/flocker/control-service.key

- name: Copy control crt
  copy:
    src: bakedcerts/control.crt
    dest: /etc/flocker/control-service.crt

- name: Set control config
  template: src=templates/flocker-control.j2 dest=/etc/init/flocker-control.override

- name: register control api
  lineinfile: dest=/etc/services line='flocker-control-api       4523/tcp' insertafter=EOF

- name: register control agent
  lineinfile: dest=/etc/services line='flocker-control-agent     4524/tcp' insertafter=EOF

- service: name=flocker-control state=restarted
